<?php

namespace Arkitecht\FedEx;

/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'AdditionalLabelsDetail' => 'Arkitecht\FedEx\Structs\AdditionalLabelsDetail',
            'Address' => 'Arkitecht\FedEx\Structs\Address',
            'AlcoholDetail' => 'Arkitecht\FedEx\Structs\AlcoholDetail',
            'BrokerDetail' => 'Arkitecht\FedEx\Structs\BrokerDetail',
            'CertificateOfOriginDetail' => 'Arkitecht\FedEx\Structs\CertificateOfOriginDetail',
            'ClientDetail' => 'Arkitecht\FedEx\Structs\ClientDetail',
            'CodAddTransportationChargesDetail' => 'Arkitecht\FedEx\Structs\CodAddTransportationChargesDetail',
            'CodDetail' => 'Arkitecht\FedEx\Structs\CodDetail',
            'CommercialInvoice' => 'Arkitecht\FedEx\Structs\CommercialInvoice',
            'CommercialInvoiceDetail' => 'Arkitecht\FedEx\Structs\CommercialInvoiceDetail',
            'CommitDetail' => 'Arkitecht\FedEx\Structs\CommitDetail',
            'Commodity' => 'Arkitecht\FedEx\Structs\Commodity',
            'ConfigurableLabelReferenceEntry' => 'Arkitecht\FedEx\Structs\ConfigurableLabelReferenceEntry',
            'ConsolidationKey' => 'Arkitecht\FedEx\Structs\ConsolidationKey',
            'Contact' => 'Arkitecht\FedEx\Structs\Contact',
            'ContactAndAddress' => 'Arkitecht\FedEx\Structs\ContactAndAddress',
            'ContentRecord' => 'Arkitecht\FedEx\Structs\ContentRecord',
            'CurrencyExchangeRate' => 'Arkitecht\FedEx\Structs\CurrencyExchangeRate',
            'CustomDeliveryWindowDetail' => 'Arkitecht\FedEx\Structs\CustomDeliveryWindowDetail',
            'CustomDocumentDetail' => 'Arkitecht\FedEx\Structs\CustomDocumentDetail',
            'CustomLabelBarcodeEntry' => 'Arkitecht\FedEx\Structs\CustomLabelBarcodeEntry',
            'CustomLabelBoxEntry' => 'Arkitecht\FedEx\Structs\CustomLabelBoxEntry',
            'CustomLabelDetail' => 'Arkitecht\FedEx\Structs\CustomLabelDetail',
            'CustomLabelGraphicEntry' => 'Arkitecht\FedEx\Structs\CustomLabelGraphicEntry',
            'CustomLabelPosition' => 'Arkitecht\FedEx\Structs\CustomLabelPosition',
            'CustomLabelTextBoxEntry' => 'Arkitecht\FedEx\Structs\CustomLabelTextBoxEntry',
            'CustomLabelTextEntry' => 'Arkitecht\FedEx\Structs\CustomLabelTextEntry',
            'CustomerImageUsage' => 'Arkitecht\FedEx\Structs\CustomerImageUsage',
            'CustomerReference' => 'Arkitecht\FedEx\Structs\CustomerReference',
            'CustomerSpecifiedLabelDetail' => 'Arkitecht\FedEx\Structs\CustomerSpecifiedLabelDetail',
            'CustomsClearanceDetail' => 'Arkitecht\FedEx\Structs\CustomsClearanceDetail',
            'CustomsOptionDetail' => 'Arkitecht\FedEx\Structs\CustomsOptionDetail',
            'DangerousGoodsContainer' => 'Arkitecht\FedEx\Structs\DangerousGoodsContainer',
            'DangerousGoodsDetail' => 'Arkitecht\FedEx\Structs\DangerousGoodsDetail',
            'DangerousGoodsShippersDeclarationDetail' => 'Arkitecht\FedEx\Structs\DangerousGoodsShippersDeclarationDetail',
            'DangerousGoodsSignatory' => 'Arkitecht\FedEx\Structs\DangerousGoodsSignatory',
            'DateRange' => 'Arkitecht\FedEx\Structs\DateRange',
            'DelayDetail' => 'Arkitecht\FedEx\Structs\DelayDetail',
            'DeliveryOnInvoiceAcceptanceDetail' => 'Arkitecht\FedEx\Structs\DeliveryOnInvoiceAcceptanceDetail',
            'DestinationControlDetail' => 'Arkitecht\FedEx\Structs\DestinationControlDetail',
            'Dimensions' => 'Arkitecht\FedEx\Structs\Dimensions',
            'Distance' => 'Arkitecht\FedEx\Structs\Distance',
            'DocTabContent' => 'Arkitecht\FedEx\Structs\DocTabContent',
            'DocTabContentBarcoded' => 'Arkitecht\FedEx\Structs\DocTabContentBarcoded',
            'DocTabContentZone001' => 'Arkitecht\FedEx\Structs\DocTabContentZone001',
            'DocTabZoneSpecification' => 'Arkitecht\FedEx\Structs\DocTabZoneSpecification',
            'DocumentFormatOptionsRequested' => 'Arkitecht\FedEx\Structs\DocumentFormatOptionsRequested',
            'EMailLabelDetail' => 'Arkitecht\FedEx\Structs\EMailLabelDetail',
            'EMailNotificationDetail' => 'Arkitecht\FedEx\Structs\EMailNotificationDetail',
            'EMailNotificationRecipient' => 'Arkitecht\FedEx\Structs\EMailNotificationRecipient',
            'EMailRecipient' => 'Arkitecht\FedEx\Structs\EMailRecipient',
            'EdtCommodityTax' => 'Arkitecht\FedEx\Structs\EdtCommodityTax',
            'EdtExciseCondition' => 'Arkitecht\FedEx\Structs\EdtExciseCondition',
            'EdtTaxDetail' => 'Arkitecht\FedEx\Structs\EdtTaxDetail',
            'EmailOptionsRequested' => 'Arkitecht\FedEx\Structs\EmailOptionsRequested',
            'EtdDetail' => 'Arkitecht\FedEx\Structs\EtdDetail',
            'ExportDeclarationDetail' => 'Arkitecht\FedEx\Structs\ExportDeclarationDetail',
            'ExportDetail' => 'Arkitecht\FedEx\Structs\ExportDetail',
            'ExpressFreightDetail' => 'Arkitecht\FedEx\Structs\ExpressFreightDetail',
            'ExpressFreightDetailContact' => 'Arkitecht\FedEx\Structs\ExpressFreightDetailContact',
            'FlatbedTrailerDetail' => 'Arkitecht\FedEx\Structs\FlatbedTrailerDetail',
            'FreightAddressLabelDetail' => 'Arkitecht\FedEx\Structs\FreightAddressLabelDetail',
            'FreightBaseCharge' => 'Arkitecht\FedEx\Structs\FreightBaseCharge',
            'FreightCommitDetail' => 'Arkitecht\FedEx\Structs\FreightCommitDetail',
            'FreightGuaranteeDetail' => 'Arkitecht\FedEx\Structs\FreightGuaranteeDetail',
            'FreightRateDetail' => 'Arkitecht\FedEx\Structs\FreightRateDetail',
            'FreightRateNotation' => 'Arkitecht\FedEx\Structs\FreightRateNotation',
            'FreightServiceCenterDetail' => 'Arkitecht\FedEx\Structs\FreightServiceCenterDetail',
            'FreightShipmentDetail' => 'Arkitecht\FedEx\Structs\FreightShipmentDetail',
            'FreightShipmentLineItem' => 'Arkitecht\FedEx\Structs\FreightShipmentLineItem',
            'FreightSpecialServicePayment' => 'Arkitecht\FedEx\Structs\FreightSpecialServicePayment',
            'GeneralAgencyAgreementDetail' => 'Arkitecht\FedEx\Structs\GeneralAgencyAgreementDetail',
            'HazardousCommodityContent' => 'Arkitecht\FedEx\Structs\HazardousCommodityContent',
            'HazardousCommodityDescription' => 'Arkitecht\FedEx\Structs\HazardousCommodityDescription',
            'HazardousCommodityInnerReceptacleDetail' => 'Arkitecht\FedEx\Structs\HazardousCommodityInnerReceptacleDetail',
            'HazardousCommodityOptionDetail' => 'Arkitecht\FedEx\Structs\HazardousCommodityOptionDetail',
            'HazardousCommodityPackagingDetail' => 'Arkitecht\FedEx\Structs\HazardousCommodityPackagingDetail',
            'HazardousCommodityPackingDetail' => 'Arkitecht\FedEx\Structs\HazardousCommodityPackingDetail',
            'HazardousCommodityQuantityDetail' => 'Arkitecht\FedEx\Structs\HazardousCommodityQuantityDetail',
            'HoldAtLocationDetail' => 'Arkitecht\FedEx\Structs\HoldAtLocationDetail',
            'HomeDeliveryPremiumDetail' => 'Arkitecht\FedEx\Structs\HomeDeliveryPremiumDetail',
            'InternationalControlledExportDetail' => 'Arkitecht\FedEx\Structs\InternationalControlledExportDetail',
            'InternationalTrafficInArmsRegulationsDetail' => 'Arkitecht\FedEx\Structs\InternationalTrafficInArmsRegulationsDetail',
            'LabelSpecification' => 'Arkitecht\FedEx\Structs\LabelSpecification',
            'LiabilityCoverageDetail' => 'Arkitecht\FedEx\Structs\LiabilityCoverageDetail',
            'LinearMeasure' => 'Arkitecht\FedEx\Structs\LinearMeasure',
            'Localization' => 'Arkitecht\FedEx\Structs\Localization',
            'Measure' => 'Arkitecht\FedEx\Structs\Measure',
            'Money' => 'Arkitecht\FedEx\Structs\Money',
            'NaftaCertificateOfOriginDetail' => 'Arkitecht\FedEx\Structs\NaftaCertificateOfOriginDetail',
            'NaftaCommodityDetail' => 'Arkitecht\FedEx\Structs\NaftaCommodityDetail',
            'NaftaProducer' => 'Arkitecht\FedEx\Structs\NaftaProducer',
            'NetExplosiveDetail' => 'Arkitecht\FedEx\Structs\NetExplosiveDetail',
            'Notification' => 'Arkitecht\FedEx\Structs\Notification',
            'NotificationParameter' => 'Arkitecht\FedEx\Structs\NotificationParameter',
            'Op900Detail' => 'Arkitecht\FedEx\Structs\Op900Detail',
            'PackageRateDetail' => 'Arkitecht\FedEx\Structs\PackageRateDetail',
            'PackageSpecialServicesRequested' => 'Arkitecht\FedEx\Structs\PackageSpecialServicesRequested',
            'Party' => 'Arkitecht\FedEx\Structs\Party',
            'Payment' => 'Arkitecht\FedEx\Structs\Payment',
            'Payor' => 'Arkitecht\FedEx\Structs\Payor',
            'PendingShipmentDetail' => 'Arkitecht\FedEx\Structs\PendingShipmentDetail',
            'PendingShipmentProcessingOptionsRequested' => 'Arkitecht\FedEx\Structs\PendingShipmentProcessingOptionsRequested',
            'PickupDetail' => 'Arkitecht\FedEx\Structs\PickupDetail',
            'PriorityAlertDetail' => 'Arkitecht\FedEx\Structs\PriorityAlertDetail',
            'RadioactivityDetail' => 'Arkitecht\FedEx\Structs\RadioactivityDetail',
            'RadionuclideActivity' => 'Arkitecht\FedEx\Structs\RadionuclideActivity',
            'RadionuclideDetail' => 'Arkitecht\FedEx\Structs\RadionuclideDetail',
            'RateDiscount' => 'Arkitecht\FedEx\Structs\RateDiscount',
            'RateReply' => 'Arkitecht\FedEx\Structs\RateReply',
            'RateReplyDetail' => 'Arkitecht\FedEx\Structs\RateReplyDetail',
            'RateRequest' => 'Arkitecht\FedEx\Structs\RateRequest',
            'RatedPackageDetail' => 'Arkitecht\FedEx\Structs\RatedPackageDetail',
            'RatedShipmentDetail' => 'Arkitecht\FedEx\Structs\RatedShipmentDetail',
            'Rebate' => 'Arkitecht\FedEx\Structs\Rebate',
            'RecipientCustomsId' => 'Arkitecht\FedEx\Structs\RecipientCustomsId',
            'RecommendedDocumentSpecification' => 'Arkitecht\FedEx\Structs\RecommendedDocumentSpecification',
            'RegulatoryLabelContentDetail' => 'Arkitecht\FedEx\Structs\RegulatoryLabelContentDetail',
            'RequestedPackageLineItem' => 'Arkitecht\FedEx\Structs\RequestedPackageLineItem',
            'RequestedShipment' => 'Arkitecht\FedEx\Structs\RequestedShipment',
            'ReturnAssociationDetail' => 'Arkitecht\FedEx\Structs\ReturnAssociationDetail',
            'ReturnEMailDetail' => 'Arkitecht\FedEx\Structs\ReturnEMailDetail',
            'ReturnInstructionsDetail' => 'Arkitecht\FedEx\Structs\ReturnInstructionsDetail',
            'ReturnShipmentDetail' => 'Arkitecht\FedEx\Structs\ReturnShipmentDetail',
            'Rma' => 'Arkitecht\FedEx\Structs\Rma',
            'ServiceSubOptionDetail' => 'Arkitecht\FedEx\Structs\ServiceSubOptionDetail',
            'ShipmentConfigurationData' => 'Arkitecht\FedEx\Structs\ShipmentConfigurationData',
            'ShipmentDryIceDetail' => 'Arkitecht\FedEx\Structs\ShipmentDryIceDetail',
            'ShipmentLegRateDetail' => 'Arkitecht\FedEx\Structs\ShipmentLegRateDetail',
            'ShipmentRateDetail' => 'Arkitecht\FedEx\Structs\ShipmentRateDetail',
            'ShipmentSpecialServicesRequested' => 'Arkitecht\FedEx\Structs\ShipmentSpecialServicesRequested',
            'ShipmentVariationOptionDetail' => 'Arkitecht\FedEx\Structs\ShipmentVariationOptionDetail',
            'ShippingDocumentDispositionDetail' => 'Arkitecht\FedEx\Structs\ShippingDocumentDispositionDetail',
            'ShippingDocumentEMailDetail' => 'Arkitecht\FedEx\Structs\ShippingDocumentEMailDetail',
            'ShippingDocumentEMailRecipient' => 'Arkitecht\FedEx\Structs\ShippingDocumentEMailRecipient',
            'ShippingDocumentFormat' => 'Arkitecht\FedEx\Structs\ShippingDocumentFormat',
            'ShippingDocumentPrintDetail' => 'Arkitecht\FedEx\Structs\ShippingDocumentPrintDetail',
            'ShippingDocumentSpecification' => 'Arkitecht\FedEx\Structs\ShippingDocumentSpecification',
            'SignatureOptionDetail' => 'Arkitecht\FedEx\Structs\SignatureOptionDetail',
            'SmartPostShipmentDetail' => 'Arkitecht\FedEx\Structs\SmartPostShipmentDetail',
            'SmartPostShipmentProcessingOptionsRequested' => 'Arkitecht\FedEx\Structs\SmartPostShipmentProcessingOptionsRequested',
            'Surcharge' => 'Arkitecht\FedEx\Structs\Surcharge',
            'Tax' => 'Arkitecht\FedEx\Structs\Tax',
            'TaxpayerIdentification' => 'Arkitecht\FedEx\Structs\TaxpayerIdentification',
            'TrackingId' => 'Arkitecht\FedEx\Structs\TrackingId',
            'TransactionDetail' => 'Arkitecht\FedEx\Structs\TransactionDetail',
            'UploadDocumentReferenceDetail' => 'Arkitecht\FedEx\Structs\UploadDocumentReferenceDetail',
            'VariableHandlingChargeDetail' => 'Arkitecht\FedEx\Structs\VariableHandlingChargeDetail',
            'VariableHandlingCharges' => 'Arkitecht\FedEx\Structs\VariableHandlingCharges',
            'Volume' => 'Arkitecht\FedEx\Structs\Volume',
            'Weight' => 'Arkitecht\FedEx\Structs\Weight',
            'WebAuthenticationDetail' => 'Arkitecht\FedEx\Structs\WebAuthenticationDetail',
            'WebAuthenticationCredential' => 'Arkitecht\FedEx\Structs\WebAuthenticationCredential',
            'VersionId' => 'Arkitecht\FedEx\Structs\VersionId',
        );
    }
}
